### ISSUE TITLE
arm 32-bit nightlies for JDK8 are missing from the web site

### ISSUE THREAD

**Issue by sxa** [adoptium/obsolete---adoptium.net#102]
Reported by @lumpfish 

* **Browser**: FireFox/Linux but likely insignificant

arm32 is not showing up on in the JDK8 nightly downloads at https://api.adoptium.net/v3/binary/latest/8/ea/linux/arm/jre/hotspot/normal/adoptium?project=jdk

The underlying API is able to retrieve it from https://api.adoptium.net/v3/binary/latest/8/ea/linux/arm/jre/hotspot/normal/adoptium?project=jdk so it is present which suggests a metadata problem. The equivalent buids for JDK11 and later seem to show up ok.

@johnoliver Can you check to see if there's anything obvious that might be preventing those builds from showing up?

**Comment by jeffalder** [comment]
@sxa They're showing up for me on the JDK 8 nightly downloads https://adoptium.net/nightly.html?variant=openjdk8&jvmVariant=hotspot ; Is this not what you're looking for?
