### ISSUE TITLE
Why there is no OpenJ9?

### ISSUE THREAD

**Issue by xtexx** [adoptium/obsolete---adoptium.net#129]
Why I could not find builds for OpenJ9 on adoptium.net?
I only can find them on AdoptOpenJDK.net

**Comment by tellison** [comment]
The Adoptium project charter does not allow for building OpenJ9 builds, but stay tuned as we understand that you will soon be able to get the same OpenJ9 builds you are used to receiving from a new location :-)

**Comment by xtexx** [comment]
Thanks
