### ISSUE TITLE
Website should give clear indication that Temurin releases pass the JCK

### ISSUE THREAD

**Issue by tellison** [adoptium/obsolete---adoptium.net#136]
As per the title, the Adoptium website should give clear indicator to users that the Temurin releases have passed the applicable Java SE TCK.

**Comment by tellison** [comment]
Looks like some part of this was already in place?

https://github.com/adoptium/adoptium.net/blob/3c397daccfa47e4cdce5c3d0494bc04b1289545b/src/handlebars/index.handlebars#L26

**Comment by karianna** [comment]
I've updated the front page to say TCK Compliant, but a strong TCK checkmark could also be used going forward

**Comment by smlambert** [comment]
I'd like to discuss this topic in the PMC meeting.  (also, if we are using this version of website code, I believe there is an old PR that has a checkmark indicating has passed X or Y (would be good to have differentiation between AQA and TCK), and relates to marketplace discussions also.  

EDIT: looks like @tellison found the handlebars for tick-marks already there not just in an old PR as I have recalled...
