### ISSUE TITLE
JDK 8 MSI Publisher Field Eclipse Foundation

### ISSUE THREAD

**Issue by wicalb** [adoptium/obsolete---adoptium.net#139]
The Publisher field lists Temurin and needs to be set as Eclipse Foundation

**Comment by karianna** [comment]
Thanks duplicated over at https://github.com/adoptium/installer/issues/326 - we should see the updated MSI over the next 24 hours

**Comment by wicalb** [comment]
I would like to add some urgency here as it impacts the path

C:\Program Files\Temurin\jdk-8.0.302.8-hotspot

vs

C:\Program Files\Eclipse Foundation

**Comment by wicalb** [comment]
I got the update, Thanks

**Comment by wicalb** [comment]
I got the update, Thanks
