### ISSUE TITLE
icedtea-web

### ISSUE THREAD

**Issue by wicalb** [adoptium/obsolete---adoptium.net#140]
AdoptOpenJDK jdk8u292-b10 had command line support to install with base install.

I need clarification on continued support with version 8

**Comment by karianna** [comment]
Can you try the advice in this https://blog.adoptopenjdk.net/2018/10/using-icedtea-web-browser-plug-in-with-adoptopenjdk/ blog post and see if that works for you?  We're looking to provide updated guidance but need some early testers

**Comment by wicalb** [comment]
yes I will be testing this week.
