### ISSUE TITLE
HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Development Kit

### ISSUE THREAD

**Issue by wicalb** [adoptium/obsolete---adoptium.net#149]
this key is missing C:\Users\bart>reg query "HKLM\SOFTWARE\JavaSoft\Java Development Kit" /v currentversion

HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Development Kit
    currentversion    REG_SZ    1.8

**Comment by tellison** [comment]
Believed to be duplicate of https://github.com/adoptium/installer/issues/329
