### ISSUE TITLE
Make the download message simple for new Java programmers

### ISSUE THREAD

**Issue by ge0ffrey** [adoptium/obsolete---adoptium.net#175]
Imagine you're a new Java programmer and you need a compiler.
And there's a website that offers you to download Eclipse (something your teacher told you is an IDE). Is that what's your looking for?

![image](https://user-images.githubusercontent.com/176880/133602278-2de7ab92-ceaa-4ef4-88b8-559a9c9bf534.png)

**Comment by sxa** [comment]
I agree that we need to do some work around the naming conventions as it has been a bit unclear to the uninitiated user. The answer to `What am I going to download?` is sort of "All of the above" but more specifically it is, as it says on the page, `Eclipse Temurin` which is the name of the distribution of OpenJDK build and shipped under the top level Adoptium project. As I'm sure you can appreciate, there are a lot of legal implications with the `java` trademark so we have to be quite careful about the labelling. We all wish it was simpler ;-) The Ecipse IDE is just one (albeit probably the most famous) thing shipped by the Eclipse Foundation. [Here's a full list](https://projects.eclipse.org/)

**Comment by ge0ffrey** [comment]
@sxa yes, you're 100% correct. I understand the challenge (including the trademark trouble and the fact that everyone thinks that Eclipse is just the IDE, which it isn't). But I fear being correct won't bring success.

AdoptAJdk's marketing was much more understandable:
"Download the AdoptAJDK JDK from adoptajdk.net." (1 brand)
Now its:
"Download the Eclipse Tenerium JDK from adoptium.net". (3 brands)

May I suggest to, at the very least, consider aligning the brand url and the download name.
