### ISSUE TITLE
adoptium.net/releases says java 17 but no downloads available?

### ISSUE THREAD

**Issue by maxandersen** [adoptium/obsolete---adoptium.net#176]
https://adoptium.net/releases.html?variant=openjdk17&jvmVariant=hotspot has openjdk 17 listed but no downloads available ?

**Comment by karianna** [comment]
nightlies are (should) available through the API

**Comment by maxandersen** [comment]
Yes; but the website doesn't show nightlies.

Would make sense if they did imo.

**Comment by smlambert** [comment]
https://adoptium.net/nightly.html
https://adoptium.net/nightly.html?variant=openjdk17&jvmVariant=hotspot

**Comment by maxandersen** [comment]
Not sure why you keep pointing to these other places ;)

I'm talking about the front releases page. 

It state 17 as an option but there are no downloads listed. 

![image](https://user-images.githubusercontent.com/54129/133937254-1587a360-e4ff-4e28-b7de-3d5bc1a510ef.png)

**Comment by smlambert** [comment]
I posted the nightly links in response to your comment that nightlies were not available via the web page (https://github.com/adoptium/adoptium.net/issues/176#issuecomment-922484846), so I shared the web page link for the nightlies.

We have not completed all of the activities related to the Sept JDK17 release, so not yet able to publish the releases to the webpage.  Track https://github.com/adoptium/adoptium/issues/74 for high-level status on each platform and the work that is in progress.  When AQA and TCK columns complete for a given, we can push to the website.

**Comment by maxandersen** [comment]
Ok so it is expected the front page is showing up as java 17 available but nothing present. 

If that is the case feel free to close it. I just wanted to report it in case something was pushed too early to the website.

**Comment by smlambert** [comment]
Yes, I am not sure why someone jumped the gun on adding jdk17 to the front page, we will only likely start releasing binaries tomorrow...

Leaving this open til the first ones start showing up and can mention in retrospective to not list new version if no binaries available...

**Comment by karianna** [comment]
Yeah that 17 popping up on the front page is a mistake - I'll try to
remove it
Cheers,
Martijn

**Comment by karianna** [comment]
It's not incorrect to have that option there but for the releases page, we don't have the HTML warning popping below it for some reason.  I'll dig in with George and John tomorrow (the code looks correct from my quick review).

**Comment by sxa** [comment]
Now resolved since we have the releases out on almost every platform :-) Closing
