### ISSUE TITLE
Java 17 radio option in releases page doesn't trigger the "Releases not available yet" wording.

### ISSUE THREAD

**Issue by karianna** [adoptium/obsolete---adoptium.net#177]
It's not incorrect to have that option there but for the releases page, we don't have the HTML warning popping below it for some reason.  I'll dig in with George and John tomorrow (the code looks correct from my quick review).

_Originally posted by @karianna in https://github.com/adoptium/adoptium.net/issues/176#issuecomment-922520205_

**Comment by sxa** [comment]
@karianna Is this still applicable now that we have releases or do we still need to fix it so we can have Java 18 show up?

**Comment by karianna** [comment]
> @karianna Is this still applicable now that we have releases or do we still need to fix it so we can have Java 18 show up?

Pretty sure this bug will propagate yeah

**Comment by karianna** [comment]
Requires a fix in the API as we get an empty array returned but with newlines.
