### ISSUE TITLE
winget installation method

### ISSUE THREAD

**Issue by baywet** [adoptium/obsolete---adoptium.net#181]
Hi everyone! 👋

I've been maintaining the Adoptium package on winget (and the adopt open jdk prior to that) for a while now.

It makes the installation much simpler on windows with:

```Shell
winget install --id EclipseFoundation.AdoptiumOpenJDK.16
```
(just submitted the PR for 17 [here](https://github.com/microsoft/winget-pkgs/pull/28450))

I was wondering whether we could add this install option to the install instructions, I did [find this page](https://github.com/adoptium/adoptium.net/blob/main/src/handlebars/installation.handlebars) but I'm wondering whether this is the actual source or whether there's a markdown somewhere else?
Thanks for the help!

**Comment by tellison** [comment]
Hi Vincent.

Thanks for your work maintaining the winget package.
As to your request, see the answer I wrote to Marco over on https://github.com/adoptium/website-v2/issues/667

The page you linked to above is indeed the right place.

**Comment by baywet** [comment]
@tellison thanks for the pointers!

I have added the information with adoptium/adoptium.net#185, let me know what you think. I don't want to take the work of reorganizing and splitting the pages though, I'll leave that to a maintainer after my PR gets merged.
