### ISSUE TITLE
Windows MSI doesn't install jdk where installation.html says it should

### ISSUE THREAD

**Issue by SaeedBaig** [adoptium/obsolete---adoptium.net#214]
The Installation page says that the Windows MSI installer package by default installs Temurin to `C:\Program Files\Temurin\`
<img width="960" alt="wrong_doc" src="https://user-images.githubusercontent.com/29703429/137422743-4ce8aa3b-6242-4348-a033-36ca1263f8d5.png">

However, the installer actually installs, by default, to `C:\Program Files\Eclipse Foundation\`
<img width="386" alt="temurin_location" src="https://user-images.githubusercontent.com/29703429/137422956-3822bc42-80a3-468d-bd3b-78f81c2dc5b6.png">

Confirmed locally; there was no `Temurin` folder in my `C:\Program Files`; noticed after an uninstall & reinstall that it was instead in `C:\Program Files\Eclipse Foundation\`

**Comment by karianna** [comment]
@SaeedBaig Thanks for reporting this, it's actually going to change again (sorry!) to Adoptium.  I'll keep this open until we make the code change and the doc change

**Comment by gdams** [comment]
So it now installs to `Eclipse Adoptium` and has done for some time. I've fixed the path in the website-v2 docs (https://github.com/adoptium/website-v2/commit/ddc4c89e850dfc9d43cd4ba2dab8ec6b3187fc89)
