### ISSUE TITLE
Wrong links to JREs on webpage during release cycle

### ISSUE THREAD

**Issue by Hr0bar** [adoptium/obsolete---adoptium.net#219]
* **Browser**: ALL

During the release week/days the webpage shown version often does not match the real link version for JREs (JDKs are released by Adoptium sometimes 24 hours+ before JRE):

![image](https://user-images.githubusercontent.com/6738790/138404519-d4eb761c-e082-4ed9-822d-ac8ec564fbf9.png)

**Comment by gdams** [comment]
This should be resolved now, thanks for rasing!
