### ISSUE TITLE
The website still does not mention Brew (only winget is mentioned in package managers).

### ISSUE THREAD

**Issue by karianna** [adoptium/obsolete---adoptium.net#261]
Hello,
The website still does not mention Brew (only winget is mentioned in package managers).
Is there any plan to update the documentation/place we could contribute to add it?

_Originally posted by @GauthierPLM in https://github.com/adoptium/adoptium-support/issues/382#issuecomment-1010914868_

**Comment by gdams** [comment]
Fixed in website-v2 https://eclipsefdn-adoptium-v2.netlify.app/installation
