### ISSUE TITLE
Setup URL redirects

### ISSUE THREAD

**Issue by gdams** [adoptium/obsolete---adoptium.net#29]
Please forward all requests from the following domain names to adoptium.net

- [x] Adoptium.com
- [ ] Adoptium.dev
- [x] Adoptium.io
- [x] Adoptium.org

**Comment by chrisguindon** [comment]
@eclipsewebmaster Can you help here?

**Comment by chrisguindon** [comment]
I sent an email to Webmaster, I don't have access to these domains. We will need webmaster to make this change.

**Comment by gdams** [comment]
Looks like adoptium.dev is complaining. The rest are all working now

**Comment by chrisguindon** [comment]
I've sent a note to @eclipsewebmaster  about this.

**Comment by eclipsewebmaster** [comment]
I reached out to the registrar last week as adoptium.dev seems to be in a weird state(according to whois at least).  I've also been trying to get the SSL side of this working correctly before closing it.

**Comment by eclipsewebmaster** [comment]
We've sorted the SSL end of things and adoptium.dev is redirecting as I expect.
