### ISSUE TITLE
Block contributions that include links to adoptopenjdk.net

### ISSUE THREAD

**Issue by chrisguindon** [adoptium/obsolete---adoptium.net#64]
This is related to https://github.com/adoptium/adoptium.net/issues/62

Would it be possible to write a test to make sure that we don't accept or merge any future contributions that might include a link to adoptopenjdk.net?

Something like https://github.com/JustinBeckwith/linkinator#command-usage could help us find links to that domain.

I think this would be preferable to a solution that would require us to periodically audit and scan the code.

**Comment by tellison** [comment]
Thanks for the suggestion Chris.  Such a tool may be useful to give us a heads-up for areas of interest to consider, but it would not have the required tests to meet the project's actual obligations.

**Comment by chrisguindon** [comment]
@tellison I am not sure I understand your decision.

It's a requirement from the Eclipse Foundation that adoptium.net does not include any links to adoptopenjdk.net. I should have made that clearer when I created the issue.

@gdams Is it possible to reconsider this decision to close this as won't fix? 

I don't have a strong opinion on the implementation but I am hopeful that we can solve this problem without having to periodically audit the Eclipse Adoptium websites in any manual way.

**Comment by smlambert** [comment]
I also do not have a strong opinion on the implementation, but if this is a requirement, it would be straightforward to create a github workflow that would check PRs for the presence of adoptopenjdk.net strings and alert the reviewers so they can request changes.

**Comment by tellison** [comment]
> It's a requirement from the Eclipse Foundation that adoptium.net does not include any links to adoptopenjdk.net. I should have made that clearer when I created the issue.

That is not true Chris, and unfortunately the exact terms of the obligations on the project are confidential, so I can't spell them out here or get into further discussion that will reveal what is/is not allowed.

As I understand that you are an Eclipse employee, I suggest that you talk to Mike Milinkovich or Paul Buck, both of whom are familiar with the agreement.

**Comment by chrisguindon** [comment]
Thanks, @tellison for the reply! 

I was instructed to audit and report any links to adoptopenjdk.net so that we can remove them.  I was hopeful that we could find a long-term solution so that we didn't need to periodically audit the site.

However, I was not aware that some links would be allowed when I created this issue.

**Comment by tellison** [comment]
Understood @chrisguindon, and as I say there is merit in having a "warning" or "heads-up" for items that should be reviewed, but (1) we'd need a way to allow through permissible material, and (2) there are any number of other possibilities in links and text that also need reviewing to adhere to the overall requirements, that a well-trained committer needs to understand and the PMC plus Eclipse Foundation needs to audit. Automation would be difficult, and ultimately encode terms that are confidential. 

The initial website was a copy of the old AdoptOpenJDK website - there were items that needed fixing, and I think we have been 'generous' in the actions taken to date. We'll continue to ensure that we abide by the spirit as well as the letter of the agreement.

Thank you for your help in achieving that.
