### ISSUE TITLE
Update AdoptOpenJDK links on the Adoptium.net Migration page

### ISSUE THREAD

**Issue by paulbuck** [adoptium/obsolete---adoptium.net#70]
Please remove the links to AdoptOpenJDK from the Adoptium.net Migration page (https://adoptium.net/migration.html), refer to the links in the IcedTea-Web and JDK Mission Control sections. Can they be replaced with links to Adoptium replacements?

**Comment by karianna** [comment]
@paulbuck - As these are not OpenJDK binaries (but simply other utilities) we should leave these in.  I did pick up on a few links that we missed in the first sweep as part of #77

**Comment by paulbuck** [comment]
@karianna All good, thanks for letting me know. Please go ahead and close this issue if you consider the matter resolved.
